version: '3'
#networks:
#  default:
#    external:
#      name: mynet
services:
  broker:
    image: "broker:latest"
    ports:
      - "8083:8083"
    expose:
      - 8083
  auldfellas:
    image: "auldfellas:latest"
    depends_on:
      - broker
    ports:
      - "8080:8080"
    expose:
      - 8080
  dodgydrivers:
    image: "dodgydrivers:latest"
    depends_on:
      - broker
    ports:
      - "8081:8081"
    expose:
      - 8081
  girlpower:
    image: "girlpower:latest"
    depends_on:
      - broker
    ports:
      - "8082:8082"
    expose:
      - 8082

